<?php
//
// File generated by ... on the 2014-06-24T16:01:33+0200
// Please do not edit manually
//

/**
 * Classes and menus for itop-synchro-dashboard (version 1.0.0)
 *
 * @author      iTop compiler
 * @license     http://opensource.org/licenses/AGPL-3.0
 */

//
// Menus
//

global $__comp_menus__; // ensure that the global variable is indeed global !
if (UserRights::IsAdministrator())
{
   $__comp_menus__['AdminTools'] = new MenuGroup('AdminTools', 80);
}
if (UserRights::IsAdministrator())
{
   $__comp_menus__['DataSourcesDashboard'] = new WebPageMenuNode('DataSourcesDashboard', utils::GetAbsoluteUrlAppRoot()."pages/exec.php?exec_module=itop-synchro-dashboard?exec_page=dashboard.php", $__comp_menus__['AdminTools']->GetIndex(), 12.1);
}
